#!/usr/bin/env python3
"""Regenerate the Claude plugin's bundled copy of SFSA and its generated reference files.

Single source of truth stays in python/sfsa and skills/catalog.json. Run after any change there:
    python scripts/sync_plugin.py
A test (python/tests/test_plugin.py) fails if the bundled copy drifts.
"""

import json
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLUGIN = ROOT / "claude-plugin"


def sync() -> None:
    src, dst = ROOT / "python" / "sfsa", PLUGIN / "lib" / "sfsa"
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    ref = PLUGIN / "skills" / "sfsa" / "reference"
    ref.mkdir(parents=True, exist_ok=True)
    catalog = json.loads((ROOT / "skills" / "catalog.json").read_text(encoding="utf-8"))
    lines = ["# SFSA skills catalog (generated by scripts/sync_plugin.py; do not edit)\n",
             "Call any of them with `session.execute_skill(name, **kwargs)`; `sfsa-info describe NAME` shows required arguments.\n"]
    cats: dict = {}
    for s in catalog:
        cats.setdefault(s["category"], []).append(s)
    for cat, items in cats.items():
        lines.append(f"\n## {cat}\n")
        lines += [f"- **{s['skill_number']}. `{s['name']}`**: {s['description']}" for s in items]
    (ref / "skills-catalog.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    doc = (src / "__init__.py").read_text(encoding="utf-8").split('"""')[1]
    engines = re.findall(r"^\s*\d+\.\s+.*$", doc, flags=re.M)
    (ref / "engines.md").write_text("# SFSA engines (generated by scripts/sync_plugin.py; do not edit)\n\n"
                                    + "\n".join(f"- {e.strip()}" for e in engines) + "\n", encoding="utf-8")
    print(f"synced {dst} ({sum(1 for _ in dst.rglob('*.py'))} files), {len(catalog)} skills, {len(engines)} engines")


if __name__ == "__main__":
    sync()
